config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users, controllers: { registrations: 'registrations' }

  get 'home/messages'
  get 'home/list'
  get 'specialist' => 'home#become_specialist'

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/business.rb
class Business < ActiveRecord::Base
  belongs_to :user
end

app/models/experience.rb
class Experience < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :business,:dependent => :destroy
  accepts_nested_attributes_for :business, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name,:last_name, :email, :password, :password_confirmation,:specialist,:age_limit,:experience,business_attributes: [ :id, :name, :address,:city,:postal_code,:province, :_destroy ] )}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name,:last_name, :email, :password, :password_confirmation,:specialist,:age_limit,:experience,business_attributes: [ :id, :name, :address,:city,:postal_code,:province, :_destroy ] )}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def messages
  end

  def list
  end

  def become_specialist
  	current_user.update_attributes(:pending_specialist=>true)
  	redirect_to edit_user_registration_path 
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
# A simple way to show error messages for the current devise resource. If you need
# to customize this method, you can either overwrite it in your application helpers or
# copy the views to your application.
#
# This method is intended to stay simple and it is unlikely that we are going to change
# it to add more behavior or options.
def devise_error_messages!
	return "" if resource.errors.empty?
	messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
	sentence = I18n.t("errors.messages.not_saved",
	count: resource.errors.count,
	resource: resource.class.model_name.human.downcase)
	html = <<-HTML
		<div class="alert alert-danger" id="error_explanation">
		<a href="#" data-dismiss="alert" class="close">×</a>
		<ul>
			<li style="list-style-type:none;">
				<b>#{messages}</b>
			</li>
		</ul>
	</div>
	<!-- <div id="error_explanation">
	<ul>#{messages}</ul>
	</div> -->
	HTML
	html.html_safe
end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="homepage">
   <section id="intro" class="section-intro">
      <div class="container intro-text ">
         <h1 class="text-center wow fadeInDown">Browse Completed Projects</h1>
         <div class="row mt40">
            <div class="col-xs-6 col-sm-offset-2 col-md-offset-2 col-sm-4 col-md-4 wow fadeInDown">
               <!-- dropdown -->
               <div class="dropdown customDropdown">
                  <a id="dLabel" role="button" data-toggle="dropdown" class="btn btn-primary customSelect" data-target="#" href="">
                  Project Type <span class="fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu">
                     <li><a href="#">Flooring</a></li>
                     <li class="dropdown-submenu">
                        <a tabindex="-1" href="#"><strong>Services</strong></a>
                        <ul class="dropdown-menu">
                           <li><a href="#">Service 1</a></li>
                           <li><a href="#">Service 2</a></li>
                        </ul>
                     </li>
                     <li><a href="#">Kitchen/Bathroom</a></li>
                     <li><a href="#">Remodelling</a></li>
                  </ul>
               </div>
               <!-- dropdown -->
            </div>
            <!-- col-6 -->
            <div class="col-xs-6 col-sm-4 col-md-4 wow fadeInDown">
               <div class="dropdown customDropdown">
                  <a id="dLabel" role="button" data-toggle="dropdown" class="btn btn-primary customSelect" data-target="#">
                  City <span class="fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu">
                     <li><a href="#">Toronto</a></li>
                     <li><a href="#">London</a></li>
                     <li><a href="#">Oakville</a></li>
                     <li><a href="#">Mississauga</a></li>
                  </ul>
               </div>
               <!-- dropdown -->
            </div>
            <!-- col-6 -->	
         </div>
         <!-- row -->
      </div>
   </section>
   <div class="intro-signup">
      <div class="container">
        <%= render "/layouts/alerts" %>
        <h2 class="wow fadeInDown">START YOUR CONSTRUCTION BUSINESS</h2>
        <br/>
        <p class="wow fadeInDown">
          <% if user_signed_in? %>
            <%= link_to 'Edit profile', edit_user_registration_path,:class=>"btn btn-primary btn-lg redbtn hvr-sink" %>
          <% else %>
            <%= link_to "Signup", new_user_registration_path,:class=>"btn btn-primary btn-lg redbtn hvr-sink" %>
          <% end %>
        </p>
      </div>
   </div>
</div> 

app/views/home/list.html.erb
<!-- listing -->
      <div class="listingArea">
         <div class="container">
            <div class="row">
               <div class="col-md-offset-1 col-sm-4 col-md-3 wow fadeInDown">
                  <!-- dropdown -->
                  <div class="dropdown customDropdown">
                     <a id="dLabel" role="button" data-toggle="dropdown" class="btn btn-primary customSelect" data-target="#" href="">
                     Project Type <span class="fa fa-angle-down"></span>
                     </a>
                     <ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu">
                        <li><a href="#">Flooring</a></li>
                        <li class="dropdown-submenu">
                           <a tabindex="-1" href="#"><strong>Services</strong></a>
                           <ul class="dropdown-menu">
                              <li><a href="#">Service 1</a></li>
                              <li><a href="#">Service 2</a></li>
                           </ul>
                        </li>
                        <li><a href="#">Kitchen/Bathroom</a></li>
                        <li><a href="#">Remodelling</a></li>
                     </ul>
                  </div>
                  <!-- dropdown -->
               </div>
               <!-- col-6 -->
               <div class="col-sm-4 col-md-3 wow fadeInDown">
                  <div class="dropdown customDropdown">
                     <a id="dLabel" role="button" data-toggle="dropdown" class="btn btn-primary customSelect" data-target="#">
                     City <span class="fa fa-angle-down"></span>
                     </a>
                     <ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu">
                        <li><a href="#">Toronto</a></li>
                        <li><a href="#">London</a></li>
                        <li><a href="#">Oakville</a></li>
                        <li><a href="#">Mississauga</a></li>
                     </ul>
                  </div>
                  <!-- dropdown -->
               </div>
               <!-- col-6 -->
               <div class="col-sm-4 col-md-3 wow fadeInDown">
                  <div class="dropdown customDropdown">
                     <a id="dLabel" role="button" data-toggle="dropdown" class="btn btn-primary customSelect" data-target="#">
                     Sort By <span class="fa fa-angle-down"></span>
                     </a>
                     <ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu">
                        <li><a href="#">Price Lowest</a></li>
                        <li><a href="#">Price highest</a></li>
                        <li><a href="#">Time Newest</a></li>
                        <li><a href="#">Distance Newest</a></li>
                     </ul>
                  </div>
                  <!-- dropdown -->
               </div>
               <!-- col-6 -->
            </div>
            <!-- row -->
            <!-- listingView -->
            <div class="listingView">
               <div class="row">
                  <div class="col-xs-12 col-sm-4 hvr-sink">
                     <div class="card">
                        <a class="img-card" href="">
                          <%= image_tag "img01.jpg" %>
                        </a>
                        <div class="card-content">
                           <h4 class="card-title">
                              <a href="">
                              Builder men
                              </a>
                           </h4>
                           <div class="">
                              $200
                           </div>
                        </div>
                        <div class="card-read-more">
                           <a class="btn btn-link btn-block" href="">
                           BOOKED NOW
                           </a>
                        </div>
                     </div>
                  </div>
                  <div class="col-xs-12 col-sm-4 hvr-sink">
                     <div class="card">
                        <a class="img-card" href="http://www.fostrap.com/">
                          <%= image_tag "img01.jpg" %>
                        </a>
                        <div class="card-content">
                           <h4 class="card-title">
                              <a href="">
                              Builder men
                              </a>
                           </h4>
                           <div class="">
                              $200
                           </div>
                        </div>
                        <div class="card-read-more">
                           <a class="btn btn-link btn-block" href="">
                           BOOKED NOW
                           </a>
                        </div>
                     </div>
                  </div>
                  <div class="col-xs-12 col-sm-4 hvr-sink">
                     <div class="card">
                        <a class="img-card" href="">
                          <%= image_tag "img01.jpg" %>
                        </a>
                        <div class="card-content">
                           <h4 class="card-title">
                              <a href="">
                              Builder men
                              </a>
                           </h4>
                           <div class="">
                              $200
                           </div>
                        </div>
                        <div class="card-read-more">
                           <a class="btn btn-link btn-block" href="">
                           BOOKED NOW
                           </a>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="row">
                  <div class="col-xs-12 col-sm-4 hvr-sink">
                     <div class="card">
                        <a class="img-card" href="">
                          <%= image_tag "img01.jpg" %>
                        </a>
                        <div class="card-content">
                           <h4 class="card-title">
                              <a href="">
                              Builder men
                              </a>
                           </h4>
                           <div class="">
                              $200
                           </div>
                        </div>
                        <div class="card-read-more">
                           <a class="btn btn-link btn-block" href="">
                           BOOKED NOW
                           </a>
                        </div>
                     </div>
                  </div>
                  <div class="col-xs-12 col-sm-4 hvr-sink">
                     <div class="card">
                        <a class="img-card" href="">
                          <%= image_tag "img01.jpg" %>
                        </a>
                        <div class="card-content">
                           <h4 class="card-title">
                              <a href="">
                              Builder men
                              </a>
                           </h4>
                           <div class="">
                              $200
                           </div>
                        </div>
                        <div class="card-read-more">
                           <a class="btn btn-link btn-block" href="">
                           BOOKED NOW
                           </a>
                        </div>
                     </div>
                  </div>
                  <div class="col-xs-12 col-sm-4 hvr-sink">
                     <div class="card">
                        <a class="img-card" href="">
                          <%= image_tag "img01.jpg" %>
                        </a>
                        <div class="card-content">
                           <h4 class="card-title">
                              <a href="">
                              Builder men
                              </a>
                           </h4>
                           <div class="">
                              $200
                           </div>
                        </div>
                        <div class="card-read-more">
                           <a class="btn btn-link btn-block" href="">
                           BOOKED NOW
                           </a>
                        </div>
                     </div>
                  </div>
               </div>
               <!-- row -->
               <div class="row">
                  <div class="col-xs-12 col-sm-4 hvr-sink">
                     <div class="card">
                        <a class="img-card" href="">
                        <%= image_tag "img01.jpg" %>
                        </a>
                        <div class="card-content">
                           <h4 class="card-title">
                              <a href="">
                              Builder men
                              </a>
                           </h4>
                           <div class="">
                              $200
                           </div>
                        </div>
                        <div class="card-read-more">
                           <a class="btn btn-link btn-block" href="">
                           BOOKED NOW
                           </a>
                        </div>
                     </div>
                  </div>
                  <div class="col-xs-12 col-sm-4 hvr-sink">
                     <div class="card">
                        <a class="img-card" href="">
                        <%= image_tag "img01.jpg" %>
                        </a>
                        <div class="card-content">
                           <h4 class="card-title">
                              <a href="">
                              Builder men
                              </a>
                           </h4>
                           <div class="">
                              $200
                           </div>
                        </div>
                        <div class="card-read-more">
                           <a class="btn btn-link btn-block" href="">
                           BOOKED NOW
                           </a>
                        </div>
                     </div>
                  </div>
                  <div class="col-xs-12 col-sm-4 hvr-sink">
                     <div class="card">
                        <a class="img-card" href="">
                        <%= image_tag "img01.jpg" %>
                        </a>
                        <div class="card-content">
                           <h4 class="card-title">
                              <a href="">
                              Builder men
                              </a>
                           </h4>
                           <div class="">
                              $200
                           </div>
                        </div>
                        <div class="card-read-more">
                           <a class="btn btn-link btn-block" href="">
                           BOOKED NOW
                           </a>
                        </div>
                     </div>
                  </div>
               </div>
               <!-- row -->
            </div>
            <!-- listingView -->
         </div>
         <!-- container -->
      </div>
      <!-- listing -->

app/views/layouts/_alerts.html.erb
<% if notice %>
	<div class="alert alert-info">
	  <button type="button" class="close" data-dismiss="alert">×</button>
	  <%= notice %>
	</div>
<% end %>
<% if alert %>
	<div class="alert alert-danger">
	  <button type="button" class="close" data-dismiss="alert">×</button>
	  <%= alert %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flicksar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>
		
	<!-- Header -->
  <nav class="navbar navbar-default mynav">
     <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar top-bar"></span>
            <span class="icon-bar middle-bar"></span>
            <span class="icon-bar bottom-bar"></span>
          </button>
          <%= link_to image_tag('logo.png'),root_path,:class=>"wow fadeInDown logotext" %>
           
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right wow fadeInDown">
              <% if user_signed_in? %>
                  <li><% unless current_user.specialist %>
                    <%= link_to "Become a specialist", specialist_path,:class=>"btn btn-success registerNow hvr-sink" %>
                  <% end %></li>
                  <li><a href=""><span><i class="fa fa-envelope-o fa-2x"></i></span></a></li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-home fa-2x"></i> <span class="fa fa-angle-down"></span></a>
                    <ul class="dropdown-menu">
                      <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
                      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                    </ul>
                  </li>
                <% else %>
                  <li><%= link_to "Login", new_user_session_path %></li>
                  <li><%= link_to "Signup", new_user_registration_path %></li>
                <% end %>
              </li>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
     </div>
     <!-- /.container-fluid -->
  </nav>
  <!-- Header -->
  
	<%= yield %>

	<div class="footer-bottom">
    <div class="container">
        <div class="row">
           <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 wow fadeInDown">
              <div class="copyright">
                 &copy; 2017, Ficksar, All rights reserved
              </div>
           </div>
           <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 wow fadeInDown">
              <div class="design">
                 <a href="#">Facebook </a> |  <a  href="">Twitter</a> |  <a  href="">Youtube</a>
              </div>
           </div>
        </div>
    </div>
  </div>
  <script type="text/javascript">
     new WOW().init();	
  </script>   

</body>
</html>